In [1]:
import numpy as np

__Working with ndarray__

Sytax -->
np.arange(start,stop,step,dtype=None)

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,10,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [5]:
np.arange(1,10,3)

array([1, 4, 7])

In [8]:
np.arange(1,10,2,dtype=np.float64)

array([ 1.,  3.,  5.,  7.,  9.])

__Examinig ndarray__

In [17]:
ds=np.arange(1,10,2)
ds

array([1, 3, 5, 7, 9])

In [12]:
ds.ndim

1

In [13]:
ds.shape

(5,)

In [16]:
ds.size

5

In [19]:
ds.dtype

dtype('int64')

In [20]:
ds.itemsize

8

In [23]:
x=ds.data      #the items are stored in the variable data by numpy.
list(x)

['\x01',
 '\x00',
 '\x00',
 '\x00',
 '\x00',
 '\x00',
 '\x00',
 '\x00',
 '\x03',
 '\x00',
 '\x00',
 '\x00',
 '\x00',
 '\x00',
 '\x00',
 '\x00',
 '\x05',
 '\x00',
 '\x00',
 '\x00',
 '\x00',
 '\x00',
 '\x00',
 '\x00',
 '\x07',
 '\x00',
 '\x00',
 '\x00',
 '\x00',
 '\x00',
 '\x00',
 '\x00',
 '\t',
 '\x00',
 '\x00',
 '\x00',
 '\x00',
 '\x00',
 '\x00',
 '\x00']

In [25]:
ds

array([1, 3, 5, 7, 9])

In [30]:
#Memory Usage , size in bytes
#its not excatly 40 bytes it also stores the other information such as heap and pointers.
ds.size * ds.itemsize 

40

In [31]:
%%capture timeit_results
#regular python
%timeit python_list_1 = range (1,1000)

#numpy
%timeit numpy_list_1 = np.arange (1,1000)

In [32]:
print timeit_results

100000 loops, best of 3: 8.13 us per loop
The slowest run took 35.42 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.64 us per loop



In [34]:
np.linspace(1,10,5)

array([  1.  ,   3.25,   5.5 ,   7.75,  10.  ])

In [36]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])